import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)
GPIO.setup(8, GPIO.OUT, initial=GPIO.HIGH)
GPIO.setup(10, GPIO.OUT, initial=GPIO.HIGH)
GPIO.setup(12, GPIO.OUT, initial=GPIO.HIGH)
GPIO.setup(16, GPIO.OUT, initial=GPIO.HIGH)
while True:
 GPIO.output(8, GPIO.LOW)
 GPIO.output(10, GPIO.HIGH)
 GPIO.output(12, GPIO.LOW)
 GPIO.output(16, GPIO.HIGH)
 print("high")
 sleep(2)
 GPIO.output(8, GPIO.HIGH) 
 GPIO.output(10, GPIO.LOW) 
 GPIO.output(12, GPIO.HIGH) 
 GPIO.output(16, GPIO.LOW) 
 print("low")
 sleep(2)
 GPIO.output(8, GPIO.HIGH) 
 GPIO.output(10, GPIO.HIGH) 
 GPIO.output(12, GPIO.LOW) 
 GPIO.output(16, GPIO.LOW) 
 print("low")
 sleep(2) 
 GPIO.output(8, GPIO.LOW) 
 GPIO.output(10, GPIO.LOW) 
 GPIO.output(12, GPIO.HIGH) 
 GPIO.output(16, GPIO.HIGH)
 print("low")
 sleep(2)
 GPIO.output(8, GPIO.LOW) 
 GPIO.output(10, GPIO.LOW) 
 GPIO.output(12, GPIO.LOW)
 GPIO.output(16, GPIO.LOW)
 print("stop")
 sleep(2)
