import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(8, GPIO.OUT)
GPIO.setup(10, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
wheel1_pwm = GPIO.PWM(8,1000)
wheel2_pwm = GPIO.PWM(10,1000)
wheel3_pwm = GPIO.PWM(12,1000)
wheel4_pwm = GPIO.PWM(16,1000)
wheel1_pwm.start(0)
wheel2_pwm.start(0)
wheel3_pwm.start(0)
wheel4_pwm.start(0)

while True:
	wheel1_pwm.ChangeDutyCycle(0)
	wheel2_pwm.ChangeDutyCycle(0)
	wheel3_pwm.ChangeDutyCycle(0)
	wheel4_pwm.ChangeDutyCycle(0)
	sleep(1)
	wheel1_pwm.ChangeDutyCycle(100)
	wheel2_pwm.ChangeDutyCycle(0)
	wheel3_pwm.ChangeDutyCycle(0)
	wheel4_pwm.ChangeDutyCycle(0)
	sleep(1)
	wheel1_pwm.ChangeDutyCycle(0)
	wheel2_pwm.ChangeDutyCycle(100)
	wheel3_pwm.ChangeDutyCycle(0)
	wheel4_pwm.ChangeDutyCycle(0)
	sleep(1)
	wheel1_pwm.ChangeDutyCycle(0)
	wheel2_pwm.ChangeDutyCycle(0)
	wheel3_pwm.ChangeDutyCycle(100)
	wheel4_pwm.ChangeDutyCycle(0)
	sleep(1)
	wheel1_pwm.ChangeDutyCycle(0)
	wheel2_pwm.ChangeDutyCycle(0)
	wheel3_pwm.ChangeDutyCycle(0)
	wheel4_pwm.ChangeDutyCycle(100)
	sleep(1)

